[build]
  publish = "public"
  functions = "functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
